name: Production Export
on:
  schedule:
    # every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Export Production Data
    steps:
      - uses: actions/checkout@v3
      - name: Export production dataset
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_VIEWER_TOKEN }}
        run: |
          yarn global add @sanity/cli
          cd backend && sanity install && SANITY_AUTH_TOKEN=$SANITY_AUTH_TOKEN
          sanity dataset export production backup.tar.gz
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-tarball
          path: backend/backup.tar.gz
          if-no-files-found: error
