name: Production Export
on:
  schedule:
    # every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  backup-dataset:
    runs-on: ubuntu-latest
    name: Export Production Data
    steps:
      - uses: actions/checkout@v3
      - name: Export production dataset
        uses: sanity-io/github-action-sanity@v0.4-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_VIEWER_TOKEN }}
        with:
          working-directory: ./backend
          args: dataset export production backup.tar.gz
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-tarball
          path: backend/backup.tar.gz
          if-no-files-found: error
