name: Development Dataset Import
on:
  workflow_dispatch:
jobs:
  import-dataset:
    runs-on: ubuntu-18.04
    name: Import Production Data To Development
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v2
      - name: Export production dataset
        uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_EXPORT_TOKEN }}
        with:
          args: dataset export production backups/backup.tar.gz
      - name: Upload backup.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: backup-tarball
          path: backups/backup.tar.gz
          if-no-files-found: error
      - uses: sanity-io/github-action-sanity@v0.2-alpha
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_IMPORT_TOKEN }}
        with:
          args: dataset import backups/backup.tar.gz development --replace
